name: my_app
description: "一個新的 Flutter 專案。"
# 以下這行用來防止此套件意外發佈到 pub.dev（使用 `flutter pub publish` 時）
# 私有專案推薦保留此設定。若要發佈到 pub.dev，可移除此行。
publish_to: 'none'

# 以下設定應用程式的版本與建置編號。
# 版本號格式為 三組數字，以點號分隔，例如 1.2.43
# 之後可接一個以 + 分隔的建置編號。
# 在 flutter build 時，可用 --build-name 和 --build-number 分別覆寫此處設定。
# 在 Android 上，build-name 對應 versionName，build-number 對應 versionCode。
# 詳見：https://developer.android.com/studio/publish/versioning
# 在 iOS 上，build-name 對應 CFBundleShortVersionString，build-number 對應 CFBundleVersion。
# 詳見：https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 在 Windows 上，build-name 用於主版本號、次版本號與修訂號，build-number 作為建置後綴。
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# 依賴套件列出此專案運作所需的其他套件。
# 若要自動升級到最新相容版本，可執行 `flutter pub upgrade --major-versions`。
# 或手動在下方調整版本號至 pub.dev 上最新版本。
# 欲查看有哪些套件可更新，可執行 `flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  supabase_flutter: ^2.6.0
  qr_flutter: ^4.0.0
  image_picker: ^1.1.1  # 拍照或選取照片
  url_launcher: ^6.3.0  # 打開 URL
  auto_size_text: ^3.0.0 # 自動調整文字大小
  device_info_plus: ^10.1.0
  mobile_scanner: ^7.1.2  # 添加 QR 碼掃描功能
  cupertino_icons: ^1.0.8 # 加入 Cupertino Icons 字型，用於 iOS 風格的圖示。
  flutter_blue_plus: ^1.35.12
  permission_handler: ^12.0.1
  flutter_ble_peripheral: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 下方 "flutter_lints" 套件提供一組推薦的 lint 規則，
  # 以鼓勵良好程式撰寫習慣。規則集在專案根目錄的 analysis_options.yaml 中啟用，
  # 可於該檔調整要停用或啟用的特定規則。
  flutter_lints: ^5.0.0

# 有關此檔中 Dart 部分的通用說明，請見：
# https://dart.dev/tools/pub/pubspec

# 以下區段專屬於 Flutter 套件設定。
flutter:

  # 確保包含 Material Icons 字型，以使用 material Icons 類別中的圖示。
  uses-material-design: true

  # 若要加入專案資源（assets），請參考以下範例：
#  assets:
 #   - assets/images/
  #  - assets/icons/

  # 圖片資源可包含多個解析度版本，詳見：
  # https://flutter.dev/to/resolution-aware-images

  # 若要從套件依賴中使用資源，請參考：
  # https://flutter.dev/to/asset-from-package

  # 若要加入自訂字體，請在此 flutter 區段新增 fonts，
  # 每個條目包含 family（字體族名稱）與 fonts（字體檔與屬性列表）。
  # 範例：
#  fonts:
  #  - family: LXGWWenKaiTC
#      fonts:
#        - asset: assets/fonts/LXGWWenKaiTC-Light.ttf
#          weight: 300
  #      - asset: assets/fonts/LXGWWenKaiTC-Regular.ttf
   #       weight: 400
   #     - asset: assets/fonts/LXGWWenKaiTC-Bold.ttf
  #        weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 若要使用套件依賴中的字體，請見：
  # https://flutter.dev/to/font-from-package
